Just do key generation then exit if configfile not given
Consensys/tessera pull request #362
Opened 2018-08-06 19:16 UTC by namtruong

Make arg --configfile optional

2018-08-06 19:21 UTC, prd-fox submitted a review, later dismissed

2018-08-06 19:40 UTC, Krish1979 submitted a review, later dismissed

2018-08-06 20:50 UTC, prd-fox approved these changes

2018-08-06 21:04 UTC, melowe requested changes
The logic in the else block assumes that the user can't define both configfile and keygen .

2018-08-06 21:18 UTC, melowe approved these changes

2018-08-07 08:27 UTC, SatpalSandhu61 approved these changes

2018-08-07 09:38 UTC, merged